export interface EffectProgramDefinition {
  id: string;
  coveredClauseIds: readonly string[];
  implementationKind: "runner" | "rule" | "modifier" | "damage-formula";
  testReferences: readonly string[];
  implementationLocator?: { module: string; symbol: string };
  focusedTestIds?: readonly string[];
}

// This registry is intentionally explicit. Dynamic template IDs are validated by
// their prefix and every concrete program must be added here as it is implemented.
const rawEffectProgramRegistry: Readonly<Record<string, EffectProgramDefinition>> = {
  "ability:fire-off": { id: "ability:fire-off", coveredClauseIds: ["energy-movement"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "ability:teal-dance": { id: "ability:teal-dance", coveredClauseIds: ["energy-attach", "draw"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "ability:ripening-charge": { id: "ability:ripening-charge", coveredClauseIds: ["energy-attach", "heal"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:phantom-dive": { id: "attack:phantom-dive", coveredClauseIds: ["bench-damage-counters", "choice"], implementationKind: "runner", testReferences: ["tests/engine/allocation-choice.test.ts"] },
  "attack:powerful-hand": { id: "attack:powerful-hand", coveredClauseIds: ["hand-scaled-damage"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:hilda": { id: "trainer:hilda", coveredClauseIds: ["evolution-search", "energy-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:brocks-scouting": { id: "trainer:brocks-scouting", coveredClauseIds: ["basic-or-evolution-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "passive:fairy-zone": { id: "passive:fairy-zone", coveredClauseIds: ["dragon-weakness"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:skyliner": { id: "passive:skyliner", coveredClauseIds: ["basic-free-retreat"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:power-saver": { id: "passive:power-saver", coveredClauseIds: ["team-rocket-attack-requirement"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:repelling-veil": { id: "passive:repelling-veil", coveredClauseIds: ["prevent-attack-effects"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:oh-no-you-dont": { id: "passive:oh-no-you-dont", coveredClauseIds: ["prize-reduction"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:toxic-subjugation": { id: "passive:toxic-subjugation", coveredClauseIds: ["poison-checkup"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:festival-lead": { id: "passive:festival-lead", coveredClauseIds: ["second-attack"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:spherical-shield": { id: "passive:spherical-shield", coveredClauseIds: ["bench-damage-prevention"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:flower-curtain": { id: "passive:flower-curtain", coveredClauseIds: ["bench-damage-prevention"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "attack:rapid-fire-combo": { id: "attack:rapid-fire-combo", coveredClauseIds: ["repeated-coin-damage"], implementationKind: "damage-formula", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "attack:rocket-rush": { id: "attack:rocket-rush", coveredClauseIds: ["team-rocket-scaled-damage"], implementationKind: "damage-formula", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "attack:dark-frost": { id: "attack:dark-frost", coveredClauseIds: ["team-rocket-energy-damage"], implementationKind: "damage-formula", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "attack:full-moon-rondo": { id: "attack:full-moon-rondo", coveredClauseIds: ["bench-scaled-damage"], implementationKind: "damage-formula", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "attack:bellowing-thunder": { id: "attack:bellowing-thunder", coveredClauseIds: ["energy-discard-damage"], implementationKind: "runner", testReferences: ["tests/engine/allocation-choice.test.ts"] },
  "trainer:switch": { id: "trainer:switch", coveredClauseIds: ["switch-active"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:prism-tower": { id: "stadium:prism-tower", coveredClauseIds: ["stadium-discard-draw"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:team-rocket-factory": { id: "stadium:team-rocket-factory", coveredClauseIds: ["supporter-triggered-draw"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:team-rocket-watchtower": { id: "stadium:team-rocket-watchtower", coveredClauseIds: ["colorless-ability-lock"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "tool:air-balloon": { id: "tool:air-balloon", coveredClauseIds: ["retreat-cost-reduction"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "tool:hero-cape": { id: "tool:hero-cape", coveredClauseIds: ["hp-modifier"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "tool:maximum-belt": { id: "tool:maximum-belt", coveredClauseIds: ["ex-damage-bonus"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "tool:binding-mochi": { id: "tool:binding-mochi", coveredClauseIds: ["poisoned-damage-bonus"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "tool:lillies-pearl": { id: "tool:lillies-pearl", coveredClauseIds: ["prize-reduction"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "template:attack:recoil:10": { id: "template:attack:recoil:10", coveredClauseIds: ["recoil"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "template:attack:recoil:30": { id: "template:attack:recoil:30", coveredClauseIds: ["recoil"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "template:attack:condition:poisoned": { id: "template:attack:condition:poisoned", coveredClauseIds: ["condition"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "template:trainer:heal-selected-clear:60": { id: "template:trainer:heal-selected-clear:60", coveredClauseIds: ["heal", "condition-clear"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "template:trainer:search-deck-to-hand:basic-energy:1": { id: "template:trainer:search-deck-to-hand:basic-energy:1", coveredClauseIds: ["energy-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "template:trainer:both-shuffle-draw:4": { id: "template:trainer:both-shuffle-draw:4", coveredClauseIds: ["both-player-draw"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "template:attack:draw-fixed:1": { id: "template:attack:draw-fixed:1", coveredClauseIds: ["draw"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "template:attack:draw-fixed:2": { id: "template:attack:draw-fixed:2", coveredClauseIds: ["draw"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "template:attack:recover-discard-to-hand:pokemon:1": { id: "template:attack:recover-discard-to-hand:pokemon:1", coveredClauseIds: ["discard-recovery"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "template:attack:search-deck-to-hand:pokemon:1": { id: "template:attack:search-deck-to-hand:pokemon:1", coveredClauseIds: ["pokemon-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:allure": { id: "attack:allure", coveredClauseIds: ["draw"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:invite-evil": { id: "attack:invite-evil", coveredClauseIds: ["darkness-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:traverse-time": { id: "attack:traverse-time", coveredClauseIds: ["grass-stadium-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:icicle-loop": { id: "attack:icicle-loop", coveredClauseIds: ["energy-recovery"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:shadow-bind": { id: "attack:shadow-bind", coveredClauseIds: ["retreat-lock"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:cosmic-beam": { id: "attack:cosmic-beam", coveredClauseIds: ["conditional-damage", "ignore-weakness-resistance"], implementationKind: "damage-formula", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "attack:shinobi-blade": { id: "attack:shinobi-blade", coveredClauseIds: ["any-card-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:aura-jab": { id: "attack:aura-jab", coveredClauseIds: ["discard-energy-attachment", "bench-energy-allocation"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:growl": { id: "attack:growl", coveredClauseIds: ["opponent-damage-reduction"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "attack:gemstone-mimicry": { id: "attack:gemstone-mimicry", coveredClauseIds: ["tera-attack-copy"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:mirage-barrage": { id: "attack:mirage-barrage", coveredClauseIds: ["discard-energy", "multi-target-damage"], implementationKind: "runner", testReferences: ["tests/engine/allocation-choice.test.ts"] },
  "attack:jolting-charge": { id: "attack:jolting-charge", coveredClauseIds: ["multi-type-energy-attachment"], implementationKind: "runner", testReferences: ["tests/engine/allocation-choice.test.ts"] },
  "attack:night-joker": { id: "attack:night-joker", coveredClauseIds: ["benched-attack-copy"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:push-down": { id: "attack:push-down", coveredClauseIds: ["opponent-switch"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:trading-places": { id: "attack:trading-places", coveredClauseIds: ["self-switch"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:impact-blow": { id: "attack:impact-blow", coveredClauseIds: ["named-attack-lock"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:shred": { id: "attack:shred", coveredClauseIds: ["piercing-damage"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "attack:hazardous-tail": { id: "attack:hazardous-tail", coveredClauseIds: ["recoil", "paralysis", "poison"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:ascension": { id: "attack:ascension", coveredClauseIds: ["evolution-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:superb-scissors": { id: "attack:superb-scissors", coveredClauseIds: ["piercing-damage"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "attack:thunder-raid": { id: "attack:thunder-raid", coveredClauseIds: ["bench-ex-damage", "energy-discard"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:prism-edge": { id: "attack:prism-edge", coveredClauseIds: ["attack-lock"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:blood-moon": { id: "attack:blood-moon", coveredClauseIds: ["attack-lock"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:drum-beating": { id: "attack:drum-beating", coveredClauseIds: ["attack-cost-modifier", "retreat-cost-modifier"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:wood-hammer": { id: "attack:wood-hammer", coveredClauseIds: ["recoil"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:trifrost": { id: "attack:trifrost", coveredClauseIds: ["multi-target-damage", "energy-discard"], implementationKind: "runner", testReferences: ["tests/engine/allocation-choice.test.ts"] },
  "attack:seek-inspiration": { id: "attack:seek-inspiration", coveredClauseIds: ["attack-copy", "top-card-discard"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:tantrum": { id: "attack:tantrum", coveredClauseIds: ["self-confusion"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:destined-fight": { id: "attack:destined-fight", coveredClauseIds: ["simultaneous-knockout"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:topaz-bolt": { id: "attack:topaz-bolt", coveredClauseIds: ["energy-discard"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:delightful-kiss": { id: "attack:delightful-kiss", coveredClauseIds: ["energy-search-attach"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:electromagnetic-sonar": { id: "attack:electromagnetic-sonar", coveredClauseIds: ["trainer-recovery"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:slight-shift": { id: "attack:slight-shift", coveredClauseIds: ["opponent-energy-move"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:hide": { id: "attack:hide", coveredClauseIds: ["attack-prevention"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:protect-charge": { id: "attack:protect-charge", coveredClauseIds: ["damage-reduction"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:flamebody-cannon": { id: "attack:flamebody-cannon", coveredClauseIds: ["energy-discard", "bench-damage"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:terminal-period": { id: "attack:terminal-period", coveredClauseIds: ["exact-damage-counter-ko"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:claw-darkness": { id: "attack:claw-darkness", coveredClauseIds: ["opponent-hand-discard"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:bounce-back": { id: "attack:bounce-back", coveredClauseIds: ["opponent-switch"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:summoning-jutsu": { id: "attack:summoning-jutsu", coveredClauseIds: ["pokemon-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:whirlpool": { id: "attack:whirlpool", coveredClauseIds: ["coin-flip", "opponent-energy-discard"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "attack:strange-hacking": { id: "attack:strange-hacking", coveredClauseIds: ["confusion", "damage-counter-allocation"], implementationKind: "runner", testReferences: ["tests/engine/allocation-choice.test.ts"] },
  "stadium:forest-of-vitality": { id: "stadium:forest-of-vitality", coveredClauseIds: ["same-turn-grass-evolution"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "trainer:premium-power-pro": { id: "trainer:premium-power-pro", coveredClauseIds: ["fighting-damage-bonus"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:risky-ruins": { id: "stadium:risky-ruins", coveredClauseIds: ["bench-damage-on-basic"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:surfing-beach": { id: "stadium:surfing-beach", coveredClauseIds: ["water-stadium-switch"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "ability:psychic-draw-2": { id: "ability:psychic-draw-2", coveredClauseIds: ["evolution-trigger-draw"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "ability:psychic-draw-3": { id: "ability:psychic-draw-3", coveredClauseIds: ["evolution-trigger-draw"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "tool:light-ball": { id: "tool:light-ball", coveredClauseIds: ["lightning-damage-bonus"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:nighttime-mine": { id: "stadium:nighttime-mine", coveredClauseIds: ["tera-cost-modifier"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:damp": { id: "passive:damp", coveredClauseIds: ["self-ko-ability-suppression"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:lumiose-city": { id: "stadium:lumiose-city", coveredClauseIds: ["supporter-heal"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "trainer:transformation-tome": { id: "trainer:transformation-tome", coveredClauseIds: ["evolution-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "tool:brave-bangle": { id: "tool:brave-bangle", coveredClauseIds: ["basic-damage-bonus"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "ability:metal-maker": { id: "ability:metal-maker", coveredClauseIds: ["top-deck-metal-attachment"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:eri": { id: "trainer:eri", coveredClauseIds: ["opponent-item-discard"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:hand-trimmer": { id: "trainer:hand-trimmer", coveredClauseIds: ["hand-size-disruption"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "ability:rapid-vernier": { id: "ability:rapid-vernier", coveredClauseIds: ["bench-switch-energy-move"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "stadium:community-center": { id: "stadium:community-center", coveredClauseIds: ["supporter-heal"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:festival-grounds": { id: "stadium:festival-grounds", coveredClauseIds: ["special-condition-prevention"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "tool:handheld-fan": { id: "tool:handheld-fan", coveredClauseIds: ["retreat-cost-modifier"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:jamming-tower": { id: "stadium:jamming-tower", coveredClauseIds: ["tool-suppression"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "trainer:kieran": { id: "trainer:kieran", coveredClauseIds: ["switch-or-damage-mode"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:secret-box": { id: "trainer:secret-box", coveredClauseIds: ["multi-category-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "passive:ace-nullifier": { id: "passive:ace-nullifier", coveredClauseIds: ["ace-spec-lock"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:plasma-bane": { id: "passive:plasma-bane", coveredClauseIds: ["conditional-attack-cost"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:academy-at-night": { id: "stadium:academy-at-night", coveredClauseIds: ["darkness-retreat-modifier"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:area-zero-underdepths": { id: "stadium:area-zero-underdepths", coveredClauseIds: ["expanded-bench"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "trainer:briar": { id: "trainer:briar", coveredClauseIds: ["opponent-ex-ko-prize"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:drayton": { id: "trainer:drayton", coveredClauseIds: ["top-deck-reveal"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:dusk-ball": { id: "trainer:dusk-ball", coveredClauseIds: ["pokemon-bottom-seven-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "tool:black-belt-training": { id: "tool:black-belt-training", coveredClauseIds: ["fighting-damage-bonus"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:ns-castle": { id: "stadium:ns-castle", coveredClauseIds: ["n-retreat-modifier"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "trainer:ruffian": { id: "trainer:ruffian", coveredClauseIds: ["pokemon-tool-discard"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "energy:prism": { id: "energy:prism", coveredClauseIds: ["conditional-type-supply"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:team-rocket": { id: "energy:team-rocket", coveredClauseIds: ["conditional-double-supply", "team-rocket-restriction"], implementationKind: "rule", testReferences: ["tests/cards/team-rocket-nidoking-cards.test.ts"] },
  "energy:growing-grass": { id: "energy:growing-grass", coveredClauseIds: ["grass-supply", "grass-hp-bonus"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:rocky-fighting": { id: "energy:rocky-fighting", coveredClauseIds: ["fighting-supply", "attack-effect-prevention"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:telepathic-psychic": { id: "energy:telepathic-psychic", coveredClauseIds: ["psychic-supply", "psychic-bench-search"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:mist": { id: "energy:mist", coveredClauseIds: ["colorless-supply", "attack-effect-prevention"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:legacy": { id: "energy:legacy", coveredClauseIds: ["all-type-supply", "prize-reduction"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:boomerang": { id: "energy:boomerang", coveredClauseIds: ["colorless-supply", "attack-return"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:enriching": { id: "energy:enriching", coveredClauseIds: ["colorless-supply", "attach-draw"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:ignition": { id: "energy:ignition", coveredClauseIds: ["conditional-colorless-supply", "end-turn-discard"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:neo-upper": { id: "energy:neo-upper", coveredClauseIds: ["conditional-all-type-supply"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "energy:spiky": { id: "energy:spiky", coveredClauseIds: ["colorless-supply", "damage-reflection"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "trainer:fighting-gong": { id: "trainer:fighting-gong", coveredClauseIds: ["fighting-energy-or-pokemon-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:jumbo-ice-cream": { id: "trainer:jumbo-ice-cream", coveredClauseIds: ["conditional-active-heal"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:wondrous-patch": { id: "trainer:wondrous-patch", coveredClauseIds: ["psychic-energy-attach"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:energy-recycler": { id: "trainer:energy-recycler", coveredClauseIds: ["energy-recovery"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:sacred-ash": { id: "trainer:sacred-ash", coveredClauseIds: ["pokemon-recovery"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:biancas-devotion": { id: "trainer:biancas-devotion", coveredClauseIds: ["low-hp-full-heal"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:enhanced-hammer": { id: "trainer:enhanced-hammer", coveredClauseIds: ["special-energy-discard"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:prime-catcher": { id: "trainer:prime-catcher", coveredClauseIds: ["double-switch"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:lumiose-galette": { id: "trainer:lumiose-galette", coveredClauseIds: ["active-heal-condition-clear"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:surfer": { id: "trainer:surfer", coveredClauseIds: ["switch-draw-five"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:lisias-appeal": { id: "trainer:lisias-appeal", coveredClauseIds: ["basic-gust-confusion"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:precious-trolley": { id: "trainer:precious-trolley", coveredClauseIds: ["basic-pokemon-bench-search"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "trainer:azs-tranquility": { id: "trainer:azs-tranquility", coveredClauseIds: ["switch-and-ex-heal"], implementationKind: "runner", testReferences: ["tests/cards/semantic-coverage.test.ts"] },
  "tool:lucky-helmet": { id: "tool:lucky-helmet", coveredClauseIds: ["damage-triggered-draw"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "stadium:gravity-mountain": { id: "stadium:gravity-mountain", coveredClauseIds: ["stage2-hp-reduction"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:wild-growth": { id: "passive:wild-growth", coveredClauseIds: ["double-grass-energy"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:mysterious-rock-inn": { id: "passive:mysterious-rock-inn", coveredClauseIds: ["prevent-ex-damage"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:incandescent-body": { id: "passive:incandescent-body", coveredClauseIds: ["burn-attacker"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:seasoned-skill": { id: "passive:seasoned-skill", coveredClauseIds: ["blood-moon-cost-reduction"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:compound-eyes": { id: "passive:compound-eyes", coveredClauseIds: ["ability-target-damage-bonus"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:sunny-day": { id: "passive:sunny-day", coveredClauseIds: ["grass-fire-damage-bonus"], implementationKind: "modifier", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
  "passive:resolute-heart": { id: "passive:resolute-heart", coveredClauseIds: ["full-hp-ko-prevention"], implementationKind: "rule", testReferences: ["tests/engine/shared-mechanics.test.ts"] },
};

export const effectProgramRegistry: Readonly<Record<string, EffectProgramDefinition>> = Object.fromEntries(
  Object.entries(rawEffectProgramRegistry).map(([id, definition]) => [id, {
    ...definition,
    implementationLocator: definition.implementationLocator ?? {
      module: definition.implementationKind === "runner" ? "engine/effects/program-runner.ts" : "engine/rules/reducer.ts",
      symbol: definition.implementationKind === "runner" ? "startEffectProgram" : definition.implementationKind,
    },
    focusedTestIds: definition.focusedTestIds ?? definition.testReferences.map((reference) => reference.replace(/^tests\//, "").replace(/\.test\.tsx?$/, "")),
  }]),
);

export function isRegisteredEffectProgram(programId: string): boolean {
  return Boolean(effectProgramRegistry[programId]);
}
