import { buildAbilitySignatureCatalogue, compileCardImplementation, implementationResolver, normalizeAbilityText, normalizeCardName, type AbilitySignatureRecord, type CatalogueIndex, type PokemonCardMetadata, type StrategicTag } from "../../data/pokemon";
import type { CardRoleProfile } from "./types";

function attackTags(card: PokemonCardMetadata): StrategicTag[] { const tags = new Set<StrategicTag>(); for (const attack of card.attacks ?? []) { const damage = Number(attack.damage.replace(/\D/g, "")); if (damage >= 180) tags.add("primary-attacker"); else if (damage >= 80) tags.add("secondary-attacker"); if (/poison/i.test(attack.text)) tags.add("poison"); if (/heal/i.test(attack.text)) tags.add("healing"); if (/attach.*energy/i.test(attack.text)) tags.add("energy-acceleration"); if (/bench/i.test(attack.text) && /damage/i.test(attack.text)) tags.add("bench-support"); } return [...tags]; }
function trainerEnergyTags(card: PokemonCardMetadata): StrategicTag[] { const text = `${card.trainerText ?? ""} ${card.energyText ?? ""} ${(card.rules ?? []).join(" ")}`.toLowerCase(); const tags = new Set<StrategicTag>(); if (/draw/.test(text)) tags.add("draw"); if (/search.*pokemon/.test(text)) tags.add("pokemon-search"); if (/search.*energy/.test(text)) tags.add("energy-search"); if (/switch/.test(text)) tags.add(/opponent/.test(text) ? "gust" : "switching"); if (/heal/.test(text)) tags.add("healing"); if (/discard pile/.test(text) && /(put|shuffle).*deck|put.*hand/.test(text)) tags.add("discard-recovery"); return [...tags]; }
const abilityCache = new WeakMap<object, AbilitySignatureRecord[]>();
function abilityCatalogue(index: CatalogueIndex): AbilitySignatureRecord[] { let value = abilityCache.get(index); if (!value) { value = buildAbilitySignatureCatalogue(index.cards); abilityCache.set(index, value); } return value; }

export function buildCardRoleProfile(card: PokemonCardMetadata, index: CatalogueIndex): CardRoleProfile {
  const abilities = abilityCatalogue(index).filter((record) => (card.abilities ?? []).some((ability) => normalizeCardName(ability.name) === normalizeCardName(record.name) && normalizeAbilityText(ability.text) === record.normalizedText && normalizeCardName(ability.type) === normalizeCardName(record.abilityType)));
  const implementation = compileCardImplementation(card); const equivalents = implementationResolver()?.equivalentsFor(card.id) ?? [card];
  const evolutionFamily = [card.name]; let cursor = card.evolvesFrom; while (cursor) { evolutionFamily.unshift(cursor); const prior = index.byName.get(normalizeCardName(cursor))?.[0]; cursor = prior?.evolvesFrom; }
  const maximumPrintedDamage = Math.max(0, ...(card.attacks ?? []).map((attack) => /^\d+$/.test(attack.damage) ? Number(attack.damage) : 0)) || undefined;
  return { cardId: card.id, evolutionFamily, stage: card.stage, hp: card.hp, types: card.types ?? [], ruleBoxCategory: card.ruleBoxText?.length || card.subtypes.some((value) => /ex|V|GX|Radiant/i.test(value)) ? "rule-box" : "single-prize", attackCosts: (card.attacks ?? []).map((attack) => attack.energy), maximumPrintedDamage, abilityTags: [...new Set(abilities.flatMap((ability) => ability.reviewedTags.length ? ability.reviewedTags : ability.inferredTags))], attackTags: attackTags(card), retreatBurden: card.retreat, prizeValue: card.subtypes.some((value) => /VMAX/i.test(value)) ? 3 : card.subtypes.some((value) => /ex|EX|VSTAR|Pokemon V/i.test(value)) ? 2 : 1, simulationSupport: implementation.status, functionalEquivalents: equivalents.map((value) => value.id), trainerEnergyRoles: trainerEnergyTags(card) };
}
