import type { CardDefinition } from "../../../engine/model/cards";
import type { DeckDefinition } from "../../../engine/model/decks";
import { runBatch } from "../../../engine/simulation/batch-runner";
import type { DeckManifest } from "../../data/decks/types";
import { toRuntimeCardDefinition, type CatalogueIndex } from "../../data/pokemon";
import type { ArchitectCandidate, CandidateSimulationSummary, GauntletPlan } from "./types";
import { measureAnchorContribution } from "./anchor-contribution";

function engineDeck(deck: DeckManifest): DeckDefinition { return { id: deck.id, name: deck.name, description: deck.description, entries: deck.entries, available: true }; }
function gameCounts(opponents: number, plan: GauntletPlan): number[] { if (typeof plan === "number") return Array.from({ length: opponents }, () => plan); if (plan.totalGames) { const base = Math.floor(plan.totalGames / opponents), remainder = plan.totalGames % opponents; return Array.from({ length: opponents }, (_, index) => base + Number(index < remainder)); } return Array.from({ length: opponents }, () => plan.gamesPerOpponent ?? 20); }
function semanticUsage(games: Array<{ playerOneEvents: Array<{ type: string; detail?: string }> }>, type: string): Record<string, number> { const totals: Record<string, number> = {}; for (const game of games) for (const event of game.playerOneEvents) if (event.type === type) { const key = event.detail ?? type; totals[key] = (totals[key] ?? 0) + 1; } return Object.fromEntries(Object.entries(totals).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))); }
export async function runQuickGauntlet(candidate: ArchitectCandidate, opponents: readonly DeckManifest[], index: CatalogueIndex, plan: GauntletPlan = 20): Promise<CandidateSimulationSummary> {
  if (!candidate.simulationReady) throw new Error("Creative or unsupported candidates cannot be simulated.");
  const ids = [...new Set([...candidate.deck.entries, ...opponents.flatMap((deck) => deck.entries)].map((entry) => entry.cardId))]; const cards = ids.map((id) => index.byId.get(id)).map((card) => card ? toRuntimeCardDefinition(card) : null).filter((card): card is CardDefinition => Boolean(card)); if (cards.length !== ids.length) throw new Error("Simulation-ready mode produced a missing runtime card.");
  const counts = gameCounts(opponents.length, plan); const batches = []; for (let opponentIndex = 0; opponentIndex < opponents.length; opponentIndex += 1) { await Promise.resolve(); const opponent = opponents[opponentIndex]!; batches.push({ opponent, result: runBatch({ games: counts[opponentIndex]!, baseSeed: candidate.seed + opponentIndex * 10_000, subjectDeck: engineDeck(candidate.deck), opponentDeck: engineDeck(opponent), cards, agentType: "heuristic", firstPlayerPolicy: "alternate" }) }); }
  const games = batches.flatMap((batch) => batch.result.games); const wins = games.filter((game) => game.result.winnerId === "player-one").length; const losses = games.filter((game) => game.result.loserId === "player-one").length; const goingFirst = games.filter((game) => game.startingPlayer === "player-one"), goingSecond = games.filter((game) => game.startingPlayer === "player-two"); const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
  const commonLossReasons = games.filter((game) => game.result.loserId === "player-one").reduce<Record<string, number>>((totals, game) => { totals[game.result.reason] = (totals[game.result.reason] ?? 0) + 1; return totals; }, {}); const cardUsage = games.reduce<Record<string, number>>((totals, game) => { for (const cardId of new Set([...game.playerOneSetupCardIds, ...game.playerOneEvents.flatMap((event) => event.sourceCardId ?? [])])) totals[cardId] = (totals[cardId] ?? 0) + 1; return totals; }, {}); const setupFailures = games.filter((game) => game.firstAttackTurn === null).length; const anchorCardId = candidate.requiredCardIds[0]; const anchorContribution = anchorCardId ? measureAnchorContribution(candidate, anchorCardId, games, index) : undefined; const mainAttackerReady = anchorContribution?.enteredPlayGames ?? 0; const definingEvents = anchorCardId ? games.reduce<Record<string, number>>((totals, game) => { for (const event of game.playerOneEvents.filter((value) => value.sourceCardId === anchorCardId && ["ability-used", "attack-used", "damage-dealt", "damage-healed", "damage-counters-moved", "damage-allocation", "special-condition-applied", "enhanced-poison-applied", "poison-checkup-damage", "energy-attached-by-effect", "energy-moved", "damage-modifier-applied", "temporary-effect-applied", "prize-modified"].includes(value.type))) { const key = `${event.type}:${event.detail ?? anchorCardId}`; totals[key] = (totals[key] ?? 0) + 1; } return totals; }, {}) : {};
  return { games: games.length, wins, losses, unresolved: games.filter((game) => game.result.unresolved).length, invalidNumeric: games.reduce((sum, game) => sum + game.invalidNumericCount, 0), choiceLoops: games.filter((game) => /choice loop/i.test(game.result.reason ?? "")).length, noLegalAction: games.filter((game) => /no legal action/i.test(game.result.reason ?? "")).length, winRate: games.length ? wins / games.length * 100 : 0, byOpponent: Object.fromEntries(batches.map(({ opponent, result }, opponentIndex) => [opponent.id, { games: result.report.gamesPlayed, wins: result.report.wins, losses: result.report.losses, unresolved: result.games.filter((game) => game.result.unresolved).length, invalidNumeric: result.games.reduce((sum, game) => sum + game.invalidNumericCount, 0), choiceLoops: result.games.filter((game) => /choice loop/i.test(game.result.reason ?? "")).length, noLegalAction: result.games.filter((game) => /no legal action/i.test(game.result.reason ?? "")).length, winRate: result.report.winPercentage, deterministicSeed: candidate.seed + opponentIndex * 10_000 }])), goingFirstWinRate: goingFirst.length ? goingFirst.filter((game) => game.result.winnerId === "player-one").length / goingFirst.length * 100 : 0, goingSecondWinRate: goingSecond.length ? goingSecond.filter((game) => game.result.winnerId === "player-one").length / goingSecond.length * 100 : 0, averageTurns: average(games.map((game) => game.result.turns)), averageMulligans: average(games.map((game) => game.mulligans["player-one"])), setupFailurePercentage: games.length ? setupFailures / games.length * 100 : 0, mainAttackerReadinessPercentage: games.length ? mainAttackerReady / games.length * 100 : 0, averageFirstAttackTurn: games.some((game) => game.firstAttackTurn !== null) ? average(games.flatMap((game) => game.firstAttackTurn ?? [])) : null, averageFirstKnockOutTurn: games.some((game) => game.firstKnockOutTurn !== null) ? average(games.flatMap((game) => game.firstKnockOutTurn ?? [])) : null, energyStarvationPercentage: games.reduce((sum, game) => sum + game.totalMainTurns, 0) ? games.reduce((sum, game) => sum + game.energyMissTurns, 0) / games.reduce((sum, game) => sum + game.totalMainTurns, 0) * 100 : 0, deckOutLosses: games.filter((game) => game.result.loserId === "player-one" && game.result.reason === "deck-out").length, averagePrizesTaken: average(games.map((game) => 6 - game.finalPrizeCounts["player-one"])), commonLossReasons, cardUsage, abilityUsage: semanticUsage(games, "ability-used"), attackUsage: semanticUsage(games, "attack-used"), anchorContribution, definingEvents, uncertainty: games.length <= opponents.length * 20 ? "Small-sample quick test; treat matchup percentages as directional, not a stable win-rate estimate." : "Larger deterministic batch; matchup variance still depends on the current heuristic agents." };
}
