import type { DeckPackage } from "./types";

// Reviewed role packages are intentionally separate from the source-backed
// tournament shells. They describe capability chains the Architect may select
// without pretending that every catalogue printing is executable.
export const additionalDeckPackages: DeckPackage[] = [
  { id:"basic-pokemon-setup", name:"Basic Pokémon setup", requiredCards:[{cardId:"sv1-196",count:4},{cardId:"sv4pt5-80",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:["Basic"], compatibleTraits:[], conflicts:[], strategicTags:["setup","search" as never], explanation:"Nest Ball and an Item search provider establish a Basic Pokémon before evolution packages are committed.", simulationReady:true },
  { id:"low-hp-basic-setup", name:"Low-HP Basic setup", requiredCards:[{cardId:"sv5-144",count:2},{cardId:"sv1-181",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:["Basic"], compatibleTraits:[], conflicts:[], strategicTags:["setup","draw"], explanation:"A low-HP Basic shell prioritises immediate draw and recovery so the opening attacker is not stranded.", simulationReady:true },
  { id:"stage1-evolution", name:"Stage 1 evolution", requiredCards:[{cardId:"sv1-181",count:2},{cardId:"sv1-196",count:3}], optionalCards:[], compatibleTypes:[], compatibleStages:["Stage 1"], compatibleTraits:[], conflicts:["rare-candy-stage-two"], strategicTags:["evolution","setup"], explanation:"Stage 1 lines preserve a real intermediate body and do not spend Rare Candy slots.", simulationReady:true },
  { id:"rare-candy-stage-two", name:"Stage 2 Rare Candy", requiredCards:[{cardId:"me1-125",count:3},{cardId:"sv1-181",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:["Stage 2"], compatibleTraits:[], conflicts:["stage1-evolution"], strategicTags:["evolution","setup"], explanation:"Rare Candy is selected only when the Basic and Stage 2 line can both be searched and the first-turn restriction is respected.", simulationReady:true },
  { id:"general-pokemon-search", name:"General Pokémon search", requiredCards:[{cardId:"me1-131",count:4},{cardId:"sv1-196",count:4}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["setup"], explanation:"Ultra Ball plus Nest Ball gives deterministic Basic and evolution access with explicit discard costs.", simulationReady:true },
  { id:"evolution-search", name:"Evolution search", requiredCards:[{cardId:"sv4-163",count:2},{cardId:"me1-125",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:["Stage 1","Stage 2"], compatibleTraits:[], conflicts:[], strategicTags:["evolution","setup"], explanation:"Evolution Incense and Rare Candy are reserved for lines whose intermediate requirements are present.", simulationReady:true },
  { id:"hand-refresh", name:"Hand refresh", requiredCards:[{cardId:"sv1-181",count:2},{cardId:"sv1-198",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["draw"], explanation:"Professor's Research style refresh is paired with a discard-aware engine and never counted as hand growth.", simulationReady:true },
  { id:"hand-growth", name:"Hand growth", requiredCards:[{cardId:"me1-119",count:2},{cardId:"sv1-189",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["draw"], explanation:"Hand growth supports Alakazam's Powerful Hand and other hand-size requirements without discarding the setup hand blindly.", simulationReady:true },
  { id:"topdeck-control", name:"Top-deck control", requiredCards:[{cardId:"sv6pt5-54",count:2},{cardId:"sv7-58",count:2}], optionalCards:[], compatibleTypes:["Psychic"], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["control","draw"], explanation:"Academy at Night and Slowking are selected as a timing pair for top-deck dependent attacks.", simulationReady:true },
  { id:"supporter-search", name:"Supporter search", requiredCards:[{cardId:"sv5-144",count:2},{cardId:"sv10-178",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["setup","draw"], explanation:"Supporter search is explicit rather than assumed: the package pays its own setup cost before counting the Supporter payoff.", simulationReady:true },
  { id:"trainer-search", name:"Trainer search", requiredCards:[{cardId:"sv4-163",count:2},{cardId:"me1-131",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["setup"], explanation:"Trainer search is a separate capability chain from Pokémon search and is only selected when the deck has meaningful Item/Supporter targets.", simulationReady:true },
  { id:"basic-energy-search", name:"Basic Energy search", requiredCards:[{cardId:"sv6-143",count:2},{cardId:"sv5-153",count:2}], optionalCards:[], compatibleTypes:["Grass"], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["setup","acceleration"], explanation:"Basic Energy search is type-specific and accounts for top-seven visibility rather than promising unconditional deck access.", simulationReady:true },
  { id:"multitype-energy-search", name:"Multi-type Energy search", requiredCards:[{cardId:"sv7-133",count:2},{cardId:"sv10-174",count:2}], optionalCards:[], compatibleTypes:["Grass","Water","Psychic","Lightning"], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["acceleration","toolbox"], explanation:"Crispin-style search requires two different Basic Energy types and is rejected when the attack plan is single-type.", simulationReady:true },
  { id:"discard-setup", name:"Discard setup", requiredCards:[{cardId:"me1-131",count:3},{cardId:"sv1-181",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["discard","setup"], explanation:"Discard setup creates a deliberate resource for recovery or discard-based attacks rather than treating every discard as free.", simulationReady:true },
  { id:"discard-recovery", name:"Discard recovery", requiredCards:[{cardId:"sv6pt5-61",count:2},{cardId:"sv2-188",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["discard","draw"], explanation:"Recovery returns the specific Energy or Pokémon resource consumed by the selected engine.", simulationReady:true },
  { id:"pokemon-recovery", name:"Pokémon recovery", requiredCards:[{cardId:"sv6pt5-61",count:2},{cardId:"me2pt5-183",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["draw"], explanation:"Pokémon recovery protects single-prize and evolution lines from prize-trade collapse.", simulationReady:true },
  { id:"energy-recovery", name:"Energy recovery", requiredCards:[{cardId:"sv2-188",count:2},{cardId:"sv5-153",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["acceleration","discard"], explanation:"Energy recovery is selected only when the attack plan actually discards or shuffles Energy.", simulationReady:true },
  { id:"switching", name:"Switching", requiredCards:[{cardId:"me1-130",count:2},{cardId:"sv6pt5-57",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["setup"], explanation:"Switching closes the gap between a poison provider and an attacker and is budgeted against retreat costs.", simulationReady:true },
  { id:"gust", name:"Gust", requiredCards:[{cardId:"me1-114",count:2},{cardId:"sv1-189",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["control"], explanation:"Gust is a target-selection package, not a generic damage upgrade; it is prioritised for spread and prize mapping.", simulationReady:true },
  { id:"tool-search", name:"Tool search", requiredCards:[{cardId:"sv6-131",count:2},{cardId:"sv4pt5-84",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["setup"], explanation:"Tool search is required before Binding Mochi, Brute Bonnet or defensive Tool plans are treated as executable.", simulationReady:true },
  { id:"stadium-search", name:"Stadium search", requiredCards:[{cardId:"sv5-153",count:2},{cardId:"sv4-163",count:2}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["setup","control"], explanation:"Stadium search protects Forest of Vitality, Magma Basin and Area Zero timing windows.", simulationReady:true },
  { id:"poison-tool", name:"Poison Tool package", requiredCards:[{cardId:"sv8pt5-95",count:2},{cardId:"svp-129",count:1}], optionalCards:[], compatibleTypes:["Darkness"], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["poison","damage-modifier" as never], explanation:"Poison Tool cards are paired with a provider such as Pecharunt or Brute Bonnet and never counted as passive damage by themselves.", simulationReady:true },
  { id:"damage-tool", name:"Damage Tool package", requiredCards:[{cardId:"me3-81",count:2},{cardId:"sv6-131",count:1}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["aggressive"], explanation:"Damage Tools are reserved for attackers whose printed threshold is actually crossed by the modifier.", simulationReady:true },
  { id:"hp-tool", name:"HP Tool package", requiredCards:[{cardId:"me2pt5-183",count:2},{cardId:"sv6-131",count:1}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["defence" as never], explanation:"HP Tools are selected for survival math and prize mapping, not as generic filler.", simulationReady:true },
  { id:"control-disruption", name:"Control and disruption", requiredCards:[{cardId:"sv6pt5-57",count:2},{cardId:"me1-117",count:1}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["control"], explanation:"Control packages identify the exact lock or target restriction and preserve a legal path for the opponent's choices.", simulationReady:true },
  { id:"ace-spec-selection", name:"ACE SPEC selection", requiredCards:[{cardId:"sv6-131",count:1}], optionalCards:[], compatibleTypes:[], compatibleStages:[], compatibleTraits:[], conflicts:[], strategicTags:["setup"], explanation:"Exactly one ACE SPEC slot is reserved and candidate mutation rejects duplicate ACE SPEC cards.", simulationReady:true },
  { id:"team-rocket-supporters", name:"Team Rocket Supporter package", requiredCards:[{cardId:"sv10-170",count:2},{cardId:"sv10-171",count:3},{cardId:"sv10-178",count:2}], optionalCards:[], compatibleTypes:["Darkness","Psychic"], compatibleStages:[], compatibleTraits:["Team Rocket's"], conflicts:[], strategicTags:["setup","draw"], explanation:"Factory and Transceiver only pay off when enough Team Rocket's Supporters and qualifying Pokémon remain in play.", simulationReady:true },
  { id:"festival-lead", name:"Festival Lead package", requiredCards:[{cardId:"sv6-25",count:2},{cardId:"sv6-143",count:2}], optionalCards:[], compatibleTypes:["Grass"], compatibleStages:[], compatibleTraits:[], conflicts:["area-zero-toolbox"], strategicTags:["setup","acceleration"], explanation:"Festival Lead packages reserve Stadium and Bench space for the double-attack engine rather than mixing unrelated Grass lines.", simulationReady:true },
  { id:"area-zero-toolbox", name:"Area Zero toolbox package", requiredCards:[{cardId:"sv7-131",count:2},{cardId:"sv7-133",count:2}], optionalCards:[], compatibleTypes:["Grass","Water","Psychic","Lightning"], compatibleStages:[], compatibleTraits:["Tera"], conflicts:["festival-lead"], strategicTags:["toolbox","bench-damage"], explanation:"Area Zero is selected only when a Tera Pokémon and a Bench-demanding toolbox are both present.", simulationReady:true },
];
