import type { DeckCardEntry, DeckManifest } from "../../data/decks/types";
import type { FormatProfile } from "../deck-import/types";
import type { StrategicTag } from "../../data/pokemon";
import type { EngineCapability, EngineRequirement } from "./engines/types";

export type ArchitectMode = "simulation-ready" | "creative";
export type ArchitectProfile = "balanced" | "turbo" | "resilient" | "control" | "aggressive";
export type SelectedCardRole = "primary-attacker" | "secondary-attacker" | "support" | "engine-core" | "tech" | "auto";
export interface FavouriteSelection { cardId: string; exactPrintingRequired: boolean; role?: SelectedCardRole; minimumCount?: number; maximumCount?: number; }
export interface ArchitectRequest { favourites: FavouriteSelection[]; format: FormatProfile; mode: ArchitectMode; candidateCount: 3 | 5 | 10; seed: number; profile?: ArchitectProfile; mustIncludeCardIds?: string[]; excludedCardIds?: string[]; maximumRuleBoxPokemon?: number; preferredAceSpecId?: string; allowSourceCopy?: boolean; preferredEnergyCountRange?: { minimum: number; maximum: number }; }
export interface SynergyEdge { fromCardId: string; toCardId: string; score: number; reasons: string[]; confidence: "reviewed" | "derived" | "inferred"; }
export interface CardRoleProfile { cardId: string; evolutionFamily: string[]; stage?: string; hp?: number; types: string[]; ruleBoxCategory: string; attackCosts: number[]; maximumPrintedDamage?: number; abilityTags: StrategicTag[]; attackTags: StrategicTag[]; retreatBurden: number; prizeValue: number; simulationSupport: string; functionalEquivalents: string[]; trainerEnergyRoles: StrategicTag[]; }
export interface ScoreBreakdown { requiredCards: number; favouriteContribution: number; evolution: number; basics: number; search: number; draw: number; energy: number; attackReadiness: number; benchSpace: number; prizeLiability: number; synergy: number; recovery: number; unsupportedPenalty: number; deadCardPenalty: number; total: number; construction?: number; favouriteRoleIntegrity?: number; openingBasicProbability?: number; setupAccess?: number; mainEnergyCoverage?: number; secondaryEnergyCoverage?: number; conflictPenalty?: number; engineCohesion?: number; simulation?: number; }
export interface ArchitectCandidate { id: string; seed: number; variant: string; requiredCardIds: string[]; deck: DeckManifest; simulationReady: boolean; score: ScoreBreakdown; explanations: string[]; synergyEdges: SynergyEdge[]; unsupportedCardIds: string[]; energyExplanation: string; fingerprint: string; quickTest?: CandidateSimulationSummary; route?: "proven" | "variation" | "hybrid" | "original"; sourceDeckId?: string; strategyPlanId?: string; sourceEvidence?: { player?: string; event?: string; placement?: number; archetype?: string }; selectedRoles?: Record<string, SelectedCardRole>; packageIds?: string[]; profile?: ArchitectProfile; trainerPlan?: import("./trainer-plan").TrainerPlan; energyPlan?: { entries: DeckCardEntry[]; mainAttackCoverage: number; secondaryAttackCoverage: number; expectedManualAttachments: number; accelerationProviders: string[]; recoveryProviders: string[]; explanation: string[]; warnings: string[] }; }
export interface SemanticCardProfile extends CardRoleProfile { behaviourFamilyId: string; roles: SelectedCardRole[]; capabilities: import("./engines/types").EngineCapability[]; requirements: import("./engines/types").EngineRequirement[]; attackPlans: Array<{ attackName: string; energy: number; damage: number; executable: boolean }>; abilityPlans: Array<{ abilityName: string; executable: boolean }>; energyDemand: Array<{ type: string; units: number; attackName: string }>; benchDemand: number; stadiumDependencies: string[]; toolDependencies: string[]; traitDependencies: string[]; discardDependencies: string[]; prizeStateDependencies: string[]; conflicts: string[]; sourceDeckIds: string[]; sourceCounts: Record<string, { average: number; minimum: number; maximum: number }>; }
export interface ArchitectKnowledgeBase { cardProfiles: Map<string, SemanticCardProfile>; engineDefinitions: Map<string, import("./engines/types").EngineDefinition>; sourcePackages: Map<string, import("./engines/types").SourceBackedPackage>; synergyChains: import("./engines/types").SynergyChain[]; strategyPlans: Map<string, import("./engines/types").DeckStrategyPlan>; sourceDecks: readonly import("../../data/decks/corpus/types").NormalizedCorpusDeck[]; cardsByCapability: Map<import("./engines/types").CapabilityKind, string[]>; cardsByRequirement: Map<import("./engines/types").RequirementKind, string[]>; decksByCardFamily: Map<string, string[]>; decksByEngine: Map<string, string[]>; }
export interface CandidateSimulationSummary { games: number; wins: number; losses: number; unresolved: number; winRate: number; byOpponent: Record<string, { games: number; wins: number; losses: number; winRate: number }>; goingFirstWinRate: number; goingSecondWinRate: number; averageTurns: number; averageMulligans: number; setupFailurePercentage: number; mainAttackerReadinessPercentage: number; averageFirstAttackTurn: number | null; averageFirstKnockOutTurn: number | null; energyStarvationPercentage: number; deckOutLosses: number; averagePrizesTaken: number; commonLossReasons: Record<string, number>; cardUsage: Record<string, number>; abilityUsage: Record<string, number>; attackUsage: Record<string, number>; uncertainty: string; }
export type GauntletPlan = number | { gamesPerOpponent?: number; totalGames?: number };
export interface ImplementationBacklogItem { cardId: string; behaviourFamilyId?: string; equivalentCardIds: string[]; missingAbilities: string[]; missingAttacks: string[]; missingEffects: string[]; candidatesBlocked: number; strategicImportance: number; }
export interface ImplementationBacklog { generatedAt: string; items: ImplementationBacklogItem[]; markdown: string; }
export interface DeckPackage {
  id: string; name: string;
  requiredCards: Array<{ cardId: string; count: number }>;
  optionalCards: Array<{ cardId: string; min: number; max: number }>;
  /** TrainerPackage ontology view retained alongside the legacy Architect fields. */
  cards?: Array<{ familyId: string; minimum: number; maximum: number; role: SelectedCardRole }>;
  requires?: EngineRequirement[];
  provides?: EngineCapability[];
  sourceDeckIds?: string[];
  reviewed?: boolean;
  compatibleTypes: string[]; compatibleStages: string[]; compatibleTraits: string[]; conflicts: string[]; strategicTags: StrategicTag[]; simulationReady: boolean; explanation: string;
}
export interface ArchitectReferenceDeck { id: string; source: "tournament" | "premade" | "reviewed-personal"; manifest: DeckManifest; engineIds: string[]; strategyPlan: import("./engines/types").DeckStrategyPlan; provenance: { label: string; event?: string; player?: string; placement?: number; reviewed: boolean; }; }
