import { compileCardImplementation, toRuntimeCardDefinition } from "../../data/pokemon";
import type { OwnedCollectionDocument, OwnedCoverageRow } from "./types";

export function buildOwnedCoverage(document: OwnedCollectionDocument): OwnedCoverageRow[] {
  const grouped = new Map<string, typeof document.entries>(); for (const entry of document.entries) grouped.set(entry.catalogueCardId, [...(grouped.get(entry.catalogueCardId) ?? []), entry]);
  return [...grouped.entries()].map(([cardId, entries]) => { const entry = entries[0]!; const implementation = compileCardImplementation(entry.canonicalMetadata); const runtime = toRuntimeCardDefinition(entry.canonicalMetadata); const printedClauses = (entry.canonicalMetadata.abilities?.length ?? 0) + (entry.canonicalMetadata.attacks?.length ?? 0) + (entry.canonicalMetadata.rules?.length ?? 0) + (entry.canonicalMetadata.trainerText ? 1 : 0) + (entry.canonicalMetadata.energyText ? 1 : 0); const coveredClauses = runtime ? printedClauses : 0; return { catalogueCardId: cardId, canonicalBehaviourCardId: entry.canonicalBehaviourCardId, gameplayFamilyId: implementation.behaviourFamilyId ?? `owned:${cardId}`, cardName: entry.metadata.name, copies: entries.reduce((sum, item) => sum + item.quantity, 0), implementationStatus: runtime && !["complete", "generated"].includes(implementation.status) ? "generated" : implementation.status, choiceSemantics: implementation.choiceSemantics ?? "exact", simulationReady: Boolean(runtime), standardLegal: entry.metadata.legalities.standard === "Legal", unknownPrograms: runtime ? [] : [implementation.handlers.map((handler) => "effectId" in handler ? handler.effectId : handler.handlerId).join(",") || `card:${cardId}`], requiresReviewChoices: implementation.choiceSemantics === "requires-review" ? [cardId] : [], printedClauses, coveredClauses }; });
}

export function ownedCoverageSummary(rows: OwnedCoverageRow[]) { return { gameplayFamilies: new Set(rows.map((row) => row.gameplayFamilyId)).size, cards: rows.length, copies: rows.reduce((sum, row) => sum + row.copies, 0), unknownPrograms: rows.flatMap((row) => row.unknownPrograms).length, choiceWarnings: rows.flatMap((row) => row.requiresReviewChoices).length, simulationReady: rows.filter((row) => row.simulationReady).length }; }
