import { useEffect, useMemo, useState, type ReactElement } from "react";
import type { OwnedCollectionDocument } from "./types";
import type { OwnedCoverageRow } from "./types";

type CoverageDocument = { summary: { gameplayFamilies: number; cards: number; copies: number; unknownPrograms: number; choiceWarnings: number; simulationReady: number }; rows: OwnedCoverageRow[] };
export function CollectionPage(): ReactElement {
  const [collection, setCollection] = useState<OwnedCollectionDocument>(); const [coverage, setCoverage] = useState<CoverageDocument>(); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all");
  useEffect(() => { void Promise.all([fetch("/data/owned-collection.json").then((response) => response.json() as Promise<OwnedCollectionDocument>), fetch("/data/owned-collection-coverage.json").then((response) => response.json() as Promise<CoverageDocument>)]).then(([nextCollection, nextCoverage]) => { setCollection(nextCollection); setCoverage(nextCoverage); }); }, []);
  const rows = useMemo(() => (coverage?.rows ?? []).filter((row) => (filter === "all" || (filter === "ready" ? row.simulationReady : row.cardName.toLocaleLowerCase().includes(filter))) && (!query.trim() || `${row.cardName} ${row.catalogueCardId}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))), [coverage, filter, query]);
  if (!collection || !coverage) return <main className="loading"><p className="eyebrow">COLLECTION</p><h1>Loading owned cards…</h1></main>;
  return <main><header className="page-heading"><div><p className="eyebrow">LOCAL · PRIVATE · QUANTITY AWARE</p><h1>Owned Collection</h1></div><p>Exact printings stay visible for quantity, set, condition and cost. Canonical behaviour IDs are used only by the executable game engine.</p></header><section className="diagnostic-stats"><article><strong>{collection.diagnostics.physicalCopies}</strong><span>physical copies</span></article><article><strong>{collection.diagnostics.distinctOwnedProducts}</strong><span>owned products</span></article><article><strong>{coverage.summary.gameplayFamilies}</strong><span>gameplay families</span></article><article><strong>{coverage.summary.simulationReady}/{coverage.summary.cards}</strong><span>simulation-ready</span></article></section><section className="panel"><p><b>Basic Energy:</b> Unlimited by default. Switch to exact quantities when you want Basic Energy reservations tracked.</p><div className="filter-grid"><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Alakazam, me1-56…" /></label><label>Filter<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All owned cards</option><option value="ready">Simulation-ready</option><option value="pokémon">Pokémon</option><option value="trainer">Trainer</option><option value="energy">Energy</option></select></label></div><div className="support-table-wrap"><table className="support-table"><thead><tr><th>Owned printing</th><th>Copies</th><th>Gameplay family</th><th>Runtime</th><th>Format</th></tr></thead><tbody>{rows.map((row) => { const entry = collection.entries.find((item) => item.catalogueCardId === row.catalogueCardId); return <tr key={row.catalogueCardId}><td><b>{entry?.productName ?? row.cardName}</b><small>{entry?.setName} · {entry?.sourceSetId} {entry?.cardNumber} · {entry?.rarity || "metadata preserved"}</small></td><td>{row.copies}<small>{entry?.pricePerUnit ?? ""} each · {entry?.totalCost ?? ""} total</small></td><td>{row.gameplayFamilyId}<small>canonical {row.canonicalBehaviourCardId}</small></td><td>{row.simulationReady ? "Ready" : "Blocked"}<small>{row.implementationStatus}</small></td><td>{row.standardLegal ? "Standard" : "Custom / Expanded"}</td></tr>; })}</tbody></table></div></section></main>;
}
