import { describe, expect, it } from "vitest";
import { applyAction, getLegalActions } from "../../engine";
import type { GameAction, PlayerId } from "../../engine/model/actions";
import type { AttackDefinition, PokemonCard } from "../../engine/model/cards";
import { canPayAttackCost } from "../../engine/rules/combat";
import { enforceAttachmentValidity } from "../../engine/rules/attachment-validity";
import { clearSpecialConditions } from "../../engine/rules/pokemon-checkup";
import { compileCardImplementation, toRuntimeCardDefinition } from "../../src/data/pokemon";
import { analyseDeck } from "../../src/features/deck-builder/validation";
import { forceTeamRocketMain, freshTeamRocketGame, teamRocketIndex, teamRocketManifest, teamRocketRuntimeCards, trInPlay, trInstance } from "../fixtures/teamRocketRuntime";

function choose(state: ReturnType<typeof freshTeamRocketGame>, playerId: PlayerId, predicate: (action: GameAction) => boolean) { const action = getLegalActions(state, playerId).find(predicate); if (!action) throw new Error(`Missing action: ${getLegalActions(state, playerId).map((item) => item.description).join(", ")}`); return applyAction(state, action); }
function ready(active = "sv10-117", opponent = "sv10-117") { const state = forceTeamRocketMain(freshTeamRocketGame()); state.players["player-one"].active = trInPlay(active, "p1-active"); state.players["player-one"].bench = []; state.players["player-two"].active = trInPlay(opponent, "p2-active"); state.players["player-two"].bench = []; return state; }
function addEnergy(pokemon: ReturnType<typeof trInPlay>, cardId: "sv10-182" | "sve-7", count: number, prefix = "energy") { pokemon.attachedEnergy.push(...Array.from({ length: count }, (_, index) => trInstance(cardId, `${prefix}-${index}`))); }
function attack(state: ReturnType<typeof freshTeamRocketGame>, name: string) { return choose(state, "player-one", (action) => action.type === "attack" && action.description.includes(name)); }

describe("Team Rocket's Nidoking exact-printing runtime support", () => {
  it("resolves 22/22 exact printings and all 60 copies as simulation-ready", () => { expect(teamRocketManifest.entries).toHaveLength(22); expect(teamRocketManifest.entries.reduce((sum, entry) => sum + entry.count, 0)).toBe(60); expect(teamRocketRuntimeCards).toHaveLength(22); for (const entry of teamRocketManifest.entries) { const card = teamRocketIndex.byId.get(entry.cardId)!; expect(compileCardImplementation(card).status).toBe("complete"); expect(toRuntimeCardDefinition(card)).not.toBeNull(); } expect(analyseDeck(teamRocketManifest, teamRocketIndex)).toMatchObject({ pokemon: 14, trainers: 36, energy: 10, unsupported: [], simulationReady: true }); });

  it("assigns reviewed Team Rocket and Pokémon ex traits without tagging support Pokémon", () => { const card = (id: string) => teamRocketRuntimeCards.find((candidate) => candidate.id === id)!; expect(card("sv10-117").traits).toContain("team-rocket"); expect(card("sv10-170").traits).toContain("team-rocket"); expect(card("sv10-119").traits).toEqual(expect.arrayContaining(["team-rocket", "pokemon-ex"])); expect(card("sv6pt5-38").traits).not.toContain("team-rocket"); });

  it("preserves Nidoran's fixed costs and resolves Horn Rend at 60 or 120 before modifiers", () => { const nidoran = teamRocketRuntimeCards.find((card): card is PokemonCard => card.id === "sv10-117" && card.category === "pokemon")!; expect(nidoran.attacks.map((item) => [item.name, item.cost, item.damage])).toMatchObject([["Pierce", { darkness: 1 }, { amount: 10 }], ["Hammer In", { darkness: 1, colorless: 1 }, { amount: 30 }]]); const run = (damage: number) => { let state = ready("sv10-118"); addEnergy(state.players["player-one"].active!, "sv10-182", 1); addEnergy(state.players["player-one"].active!, "sve-7", 1); state.players["player-two"].active!.damage = damage; state = attack(state, "Horn Rend"); return state.events.find((event) => event.type === "damage-dealt")?.amount; }; expect(run(0)).toBe(60); expect(run(10)).toBe(120); });

  it("uses one physical Team Rocket Energy as exactly two flexible units without double-counting", () => { const state = ready(); const pokemon = state.players["player-one"].active!; addEnergy(pokemon, "sv10-182", 1); const cost = (value: AttackDefinition["cost"]): AttackDefinition => ({ id: "test", name: "Test", cost: value, damage: { kind: "fixed", amount: 0, printed: "0" } }); expect(canPayAttackCost(state, pokemon, cost({ darkness: 2 }))).toBe(true); expect(canPayAttackCost(state, pokemon, cost({ psychic: 2 }))).toBe(true); expect(canPayAttackCost(state, pokemon, cost({ darkness: 1, psychic: 1 }))).toBe(true); expect(canPayAttackCost(state, pokemon, cost({ colorless: 2 }))).toBe(true); expect(canPayAttackCost(state, pokemon, cost({ colorless: 3 }))).toBe(false); addEnergy(pokemon, "sve-7", 1); expect(canPayAttackCost(state, pokemon, cost({ darkness: 2, colorless: 1 }))).toBe(true); addEnergy(pokemon, "sv10-182", 1); expect(canPayAttackCost(state, pokemon, cost({ darkness: 3, colorless: 1 }))).toBe(true); expect(pokemon.attachedEnergy.filter((item) => item.cardId === "sv10-182")).toHaveLength(2); });

  it("restricts Team Rocket Energy attachment to Team Rocket Pokémon", () => { const state = ready(); state.players["player-one"].bench = [trInPlay("sv10-118", "nidorino"), trInPlay("sv10-119", "nidoking"), trInPlay("sv6pt5-39", "pecharunt"), trInPlay("sv6pt5-38", "fez"), trInPlay("sv6pt5-72", "munkidori")]; const energy = trInstance("sv10-182", "manual"); state.players["player-one"].hand.push(energy); const targets = getLegalActions(state, "player-one").filter((action) => action.type === "attach-energy" && action.cardInstanceId === energy.instanceId).map((action) => action.description); expect(targets).toHaveLength(3); expect(targets.join(" ")).toMatch(/Nidoran/); expect(targets.join(" ")).toMatch(/Nidorino/); expect(targets.join(" ")).toMatch(/Nidoking/); expect(targets.join(" ")).not.toMatch(/Pecharunt|Fezandipiti|Munkidori/); });

  it("Tainted Horn deals 100, applies 8-counter Poison to a survivor, and Kingly Impact deals 240", () => { let state = ready("sv10-119", "sv10-119"); addEnergy(state.players["player-one"].active!, "sv10-182", 2); state = attack(state, "Tainted Horn"); expect(state.events.some((event) => event.type === "damage-dealt" && event.amount === 100)).toBe(true); expect(state.events.some((event) => event.type === "enhanced-poison-applied" && event.amount === 8)).toBe(true); expect(state.events.some((event) => event.type === "poison-checkup-damage" && event.amount === 80)).toBe(true); state = ready("sv10-119", "sv10-119"); addEnergy(state.players["player-one"].active!, "sv10-182", 2); state = attack(state, "Kingly Impact"); expect(state.players["player-two"].active!.damage).toBe(240); });

  it("clears enhanced Poison state whenever Special Conditions clear", () => { const pokemon = trInPlay("sv10-119", "poisoned"); pokemon.specialConditions.push("poisoned"); pokemon.poison = { countersPerCheckup: 8, sourceCardId: "sv10-119" }; clearSpecialConditions(pokemon); expect(pokemon.specialConditions).not.toContain("poisoned"); expect(pokemon.poison).toBeUndefined(); });

  it("Buddy-Buddy Poffin benches only eligible Basics and respects free spaces", () => { let state = ready(); state.players["player-one"].bench = Array.from({ length: 4 }, (_, index) => trInPlay("sv10-117", `occupied-${index}`)); state.players["player-one"].deck = [trInstance("sv10-117", "eligible-a"), trInstance("sv10-117", "eligible-b"), trInstance("sv6pt5-72", "too-large")]; const poffin = trInstance("sv5-144", "poffin"); state.players["player-one"].hand.push(poffin); state = choose(state, "player-one", (action) => action.type === "play-trainer" && action.cardInstanceId === poffin.instanceId); expect(state.pendingChoice).toMatchObject({ min: 0, max: 1 }); state = choose(state, "player-one", (action) => action.type === "select-card"); state = choose(state, "player-one", (action) => action.type === "confirm-choice"); expect(state.players["player-one"].bench).toHaveLength(5); expect(state.players["player-one"].bench.at(-1)!.enteredPlayTurn).toBe(state.turn); });

  it("Earthen Vessel requires another card, pays exactly one discard, and excludes Special Energy", () => { let state = ready(); const vessel = trInstance("sv4-163", "vessel"); state.players["player-one"].hand = [vessel]; expect(getLegalActions(state, "player-one").some((action) => action.type === "play-trainer")).toBe(false); state.players["player-one"].hand.push(trInstance("sv10-117", "cost")); state.players["player-one"].deck = [trInstance("sve-7", "basic"), trInstance("sv10-182", "special")]; state = choose(state, "player-one", (action) => action.type === "play-trainer"); state = choose(state, "player-one", (action) => action.type === "select-card"); state = choose(state, "player-one", (action) => action.type === "confirm-choice"); expect(state.pendingChoice?.type === "effect-choice" ? state.pendingChoice.eligibleIds : []).toEqual(["basic-sve-7"]); });

  it("Rare Candy skips Nidorino only for a settled matching Nidoran", () => { let state = ready(); const nidoran = trInPlay("sv10-117", "candy-basic"); const nidoranId = nidoran.stack.at(-1)!.instanceId; nidoran.enteredPlayTurn = state.turn - 1; state.players["player-one"].bench = [nidoran]; const candy = trInstance("sv1-191", "candy"); const nidoking = trInstance("sv10-119", "stage2"); state.players["player-one"].hand.push(candy, nidoking); state = choose(state, "player-one", (action) => action.type === "play-trainer" && action.cardInstanceId === candy.instanceId); state = choose(state, "player-one", (action) => action.type === "select-pokemon" && action.selectionId === nidoranId); state = choose(state, "player-one", (action) => action.type === "confirm-choice"); state = choose(state, "player-one", (action) => action.type === "select-card"); state = choose(state, "player-one", (action) => action.type === "confirm-choice"); expect(state.players["player-one"].bench[0]!.stack.map((item) => item.cardId)).toEqual(["sv10-117", "sv10-119"]); const fresh = ready("sv6pt5-38"); const justPlayed = trInPlay("sv10-117", "fresh"); justPlayed.enteredPlayTurn = fresh.turn; fresh.players["player-one"].bench = [justPlayed]; fresh.players["player-one"].hand = [trInstance("sv1-191", "blocked"), trInstance("sv10-119", "blocked-stage2")]; expect(getLegalActions(fresh, "player-one").some((action) => action.type === "play-trainer" && action.description.includes("Rare Candy"))).toBe(false); });

  it("Super Rod recovers only Pokémon and Basic Energy as exact instances", () => { let state = ready(); state.players["player-one"].discard = [trInstance("sv10-117", "rod-pokemon"), trInstance("sve-7", "rod-basic"), trInstance("sv10-182", "rod-special")]; const rod = trInstance("sv2-188", "rod"); state.players["player-one"].hand = [rod]; state = choose(state, "player-one", (action) => action.type === "play-trainer" && action.cardInstanceId === rod.instanceId); const eligible = state.pendingChoice?.type === "effect-choice" ? state.pendingChoice.eligibleIds : []; expect(eligible).toEqual(expect.arrayContaining(["rod-pokemon-sv10-117", "rod-basic-sve-7"])); expect(eligible).not.toContain("rod-special-sv10-182"); });

  it("gates Archer on a structured prior-opponent-turn Team Rocket KO", () => { const state = ready(); const archer = trInstance("sv10-170", "archer"); state.players["player-one"].hand.push(archer); expect(getLegalActions(state, "player-one").some((action) => action.type === "play-trainer" && action.cardInstanceId === archer.instanceId)).toBe(false); state.events.push({ index: 0, turn: state.turn - 1, type: "pokemon-knocked-out", playerId: "player-two", targetPlayerId: "player-one", detail: "sv10-117", cause: "attack-damage" }); expect(getLegalActions(state, "player-one").some((action) => action.type === "play-trainer" && action.cardInstanceId === archer.instanceId)).toBe(true); });

  it("Archer shuffles both hands and redraws exactly 5 cards for its player and 3 for the opponent", () => { let state = ready(); state.players["player-one"].hand = [trInstance("sv10-170", "archer"), trInstance("sv10-117", "own-card")]; state.players["player-two"].hand = [trInstance("sv10-117", "opponent-card-a"), trInstance("sve-7", "opponent-card-b")]; state.players["player-one"].deck = Array.from({ length: 8 }, (_, index) => trInstance("sve-7", `own-deck-${index}`)); state.players["player-two"].deck = Array.from({ length: 8 }, (_, index) => trInstance("sve-7", `opponent-deck-${index}`)); state.events.push({ index: 0, turn: state.turn - 1, type: "pokemon-knocked-out", playerId: "player-two", targetPlayerId: "player-one", detail: "sv10-117", cause: "attack-damage" }); state = choose(state, "player-one", (action) => action.type === "play-trainer" && action.cardInstanceId.endsWith("sv10-170")); expect(state.players["player-one"].hand).toHaveLength(5); expect(state.players["player-two"].hand).toHaveLength(3); expect(state.events.filter((event) => event.type === "card-played" && event.sourceCardId === "sv10-170")).toHaveLength(1); });

  it("Ariana draws to 8 only when every Pokémon in play has the Team Rocket trait", () => { const run = (support: string) => { let state = ready(); state.players["player-one"].bench = [trInPlay(support, "support")]; state.players["player-one"].deck = Array.from({ length: 10 }, (_, index) => trInstance("sve-7", `draw-${index}`)); state.players["player-one"].hand = [trInstance("sv10-171", "ariana")]; state = choose(state, "player-one", (action) => action.type === "play-trainer"); return state.players["player-one"].hand.length; }; expect(run("sv10-117")).toBe(8); expect(run("sv6pt5-38")).toBe(5); });

  it("activates Factory only after a Team Rocket Supporter and only once per turn", () => { let state = ready(); state.stadium = trInstance("sv10-173", "factory"); state.players["player-one"].deck = [trInstance("sve-7", "draw-a"), trInstance("sve-7", "draw-b")]; const before = state.players["player-one"].hand.length; expect(getLegalActions(state, "player-one").some((action) => action.type === "use-stadium")).toBe(false); state.events.push({ index: 0, turn: state.turn, type: "card-played", playerId: "player-one", sourceCardId: "sv10-176", detail: "Team Rocket Supporter" }); state = choose(state, "player-one", (action) => action.type === "use-stadium"); expect(state.players["player-one"].hand).toHaveLength(before + 2); expect(getLegalActions(state, "player-one").some((action) => action.type === "use-stadium")).toBe(false); });

  it("allows Proton alone on the first player's first turn and filters Basic Team Rocket Pokémon", () => { const state = ready(); state.turn = 1; state.players["player-one"].turnsTaken = 1; state.startingPlayer = "player-one"; state.players["player-one"].hand = [trInstance("sv10-177", "proton"), trInstance("sv10-171", "ariana")]; state.players["player-one"].deck = [trInstance("sv10-117", "nidoran"), trInstance("sv6pt5-38", "fez")]; const actions = getLegalActions(state, "player-one").filter((action) => action.type === "play-trainer"); expect(actions).toHaveLength(1); expect(actions[0]!.description).toContain("Proton"); });

  it("executes Giovanni's own Team Rocket switch before the opposing gust", () => { let state = ready(); const ownBench = trInPlay("sv10-118", "own-bench"); const opponentBench = trInPlay("sv6pt5-38", "opponent-bench"); state.players["player-one"].bench = [ownBench]; state.players["player-two"].bench = [opponentBench]; state.players["player-one"].hand = [trInstance("sv10-174", "giovanni")]; const originalOwnActiveId = state.players["player-one"].active!.stack[0]!.instanceId; const originalOpponentActiveId = state.players["player-two"].active!.stack[0]!.instanceId; state = choose(state, "player-one", (action) => action.type === "play-trainer"); state = choose(state, "player-one", (action) => action.type === "select-pokemon"); state = choose(state, "player-one", (action) => action.type === "confirm-choice"); expect(state.players["player-one"].active!.stack[0]!.instanceId).toBe("own-bench-sv10-118"); expect(state.players["player-one"].bench.map((pokemon) => pokemon.stack[0]!.instanceId)).toContain(originalOwnActiveId); state = choose(state, "player-one", (action) => action.type === "select-pokemon"); state = choose(state, "player-one", (action) => action.type === "confirm-choice"); expect(state.players["player-two"].active!.stack[0]!.instanceId).toBe("opponent-bench-sv6pt5-38"); expect(state.players["player-two"].bench.map((pokemon) => pokemon.stack[0]!.instanceId)).toContain(originalOpponentActiveId); expect(state.events.filter((event) => event.sourceCardId === "sv10-174" && event.type === "ability-used").map((event) => event.detail)).toEqual(["Giovanni own switch", "Giovanni opponent gust"]); });

  it("lets Petrel find any Trainer while Transceiver finds only Team Rocket Supporters", () => { let state = ready(); state.players["player-one"].hand = [trInstance("sv10-176", "petrel")]; state.players["player-one"].deck = [trInstance("sv5-144", "item"), trInstance("sv10-173", "stadium"), trInstance("sv10-171", "supporter"), trInstance("sv10-117", "pokemon")]; state = choose(state, "player-one", (action) => action.type === "play-trainer"); expect(state.pendingChoice?.type === "effect-choice" ? state.pendingChoice.eligibleIds : []).toEqual(expect.arrayContaining(["item-sv5-144", "stadium-sv10-173", "supporter-sv10-171"])); expect(state.pendingChoice?.type === "effect-choice" ? state.pendingChoice.eligibleIds : []).not.toContain("pokemon-sv10-117"); state = ready(); state.players["player-one"].hand = [trInstance("sv10-178", "transceiver")]; state.players["player-one"].deck = [trInstance("sv10-171", "ariana"), trInstance("sv10-176", "petrel"), trInstance("sv5-144", "item"), trInstance("sv10-173", "factory")]; state = choose(state, "player-one", (action) => action.type === "play-trainer"); expect(state.pendingChoice?.type === "effect-choice" ? state.pendingChoice.eligibleIds : []).toEqual(["ariana-sv10-171", "petrel-sv10-176"]); });

  it("limits Proton's actual search selection to Basic Team Rocket Pokémon", () => { let state = ready(); state.players["player-one"].hand = [trInstance("sv10-177", "proton")]; state.players["player-one"].deck = [trInstance("sv10-117", "basic-team-rocket"), trInstance("sv10-118", "evolution-team-rocket"), trInstance("sv6pt5-38", "basic-support")]; state = choose(state, "player-one", (action) => action.type === "play-trainer"); expect(state.pendingChoice?.type === "effect-choice" ? state.pendingChoice.eligibleIds : []).toEqual(["basic-team-rocket-sv10-117"]); });

  it("discards Team Rocket Energy if an effect leaves it attached to an ineligible Pokémon", () => { const state = ready("sv6pt5-38"); const energy = trInstance("sv10-182", "invalid"); state.players["player-one"].active!.attachedEnergy.push(energy); enforceAttachmentValidity(state); expect(state.players["player-one"].active!.attachedEnergy).toHaveLength(0); expect(state.players["player-one"].discard).toContain(energy); expect(state.events.at(-1)).toMatchObject({ type: "energy-discarded-invalid", sourceCardId: "sv10-182", targetId: "p1-active-sv6pt5-38" }); });

  it("awards exactly 2 Prizes when Team Rocket's Nidoking ex is Knocked Out", () => { let state = ready("sv10-119", "sv10-119"); state.players["player-two"].bench = [trInPlay("sv10-117", "promotion")]; addEnergy(state.players["player-one"].active!, "sv10-182", 2); state.players["player-two"].active!.damage = 250; state = attack(state, "Tainted Horn"); expect(state.pendingChoice).toMatchObject({ type: "choose-prize", claims: [{ takingPlayerId: "player-one", remaining: 2 }] }); expect(state.events.find((event) => event.type === "pokemon-knocked-out" && event.targetPlayerId === "player-two")?.amount).toBe(2); });
});
