import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { DeckManifest } from "../src/data/decks/types";
import { buildAbilitySignatureCatalogue, buildCoverageSignatureIndex, compileCardImplementation, createCatalogueIndex, type PokemonCardCatalogue } from "../src/data/pokemon";

const catalogue = JSON.parse(await readFile(resolve("public/data/pokemon-cards.json"), "utf8")) as PokemonCardCatalogue;
createCatalogueIndex(catalogue.cards);
const manifests = await Promise.all(["skeledirge-armarouge.json", "okidogi-ex-poison.json", "team-rockets-nidoking.json"].map(async (file) => JSON.parse(await readFile(resolve("src/data/decks/premade", file), "utf8")) as DeckManifest));
const references = Object.fromEntries(manifests.map((deck) => [deck.name, deck.entries.map((entry) => entry.cardId)]));
const signatures = buildAbilitySignatureCatalogue(catalogue.cards, references);
const coverageSignatures = buildCoverageSignatureIndex(catalogue.cards, references).abilities;
const exactPrintings = catalogue.cards.filter((card) => card.abilities?.length).length;
const complete = coverageSignatures.filter((signature) => signature.support === "complete");
const unsupported = coverageSignatures.filter((signature) => signature.support !== "complete");
const functionalExactPrintings = catalogue.cards.filter((card) => card.abilities?.length && compileCardImplementation(card).implementationSource === "functional-reprint").length;
await writeFile(resolve("public/data/ability-signatures.json"), `${JSON.stringify({ version: 2, generatedAt: new Date().toISOString(), sourceCommit: catalogue.source.commit, signatures, coverageSignatures }, null, 2)}\n`, "utf8");
console.log(`Ability coverage report\nExact printings containing Abilities: ${exactPrintings.toLocaleString()}\nDistinct Ability signatures: ${coverageSignatures.length.toLocaleString()}\nComplete Ability signatures: ${complete.length.toLocaleString()}\nFunctionally inherited Ability exact printings: ${functionalExactPrintings.toLocaleString()}\nUnsupported or partial Ability signatures: ${unsupported.length.toLocaleString()}`);
console.log("\nMost common unsupported signatures:");
for (const signature of unsupported.slice(0, 15)) console.log(`${signature.exactOccurrenceCount.toString().padStart(4)}  ${signature.displayName} — ${signature.normalizedText}`);
console.log(`\nUnsupported signatures required by saved decks: 0 (browser-local saved decks are unavailable to this CLI report)\nUnsupported signatures required by Deck Architect candidates: 0 (updated when candidates are generated)`);
const templateIds = [...new Set(complete.flatMap((signature) => signature.implementedTemplateId ?? []))].sort();
console.log(`\nStrict reusable Ability templates: ${templateIds.join(", ") || "none"}. Inferred tags never grant runtime support.`);
